Person Controller
Danilosimoes/people-api pull request #2
Opened 2020-06-03 22:22 UTC by Danilosimoes

Person Controller

2020-06-03 22:27 UTC, robsonoduarte commented on src/main/java/br/com/people/api/controller/PersonController.java
> +    // TODO: delete
Danilo um exemplo de como podemos ir discutindo por aqui nesse PR :rocket:

2020-06-04 23:14 UTC, Danilosimoes commented
Atualizei aqui, corrigi alguns erros, mas está dando um ultimo erro, no fechamento do ultima chave, e um import, saiu sozinho da estrutura, eu não mexi nele

2020-06-04 23:58 UTC, robsonoduarte requested changes

2020-06-04 23:58 UTC, robsonoduarte commented on src/main/java/br/com/people/api/db/DataBase.java
> +        return jdbcTemplate.update("UPDATE PERSON SET ? WHERE ID = ?",
Danilo isso não vai funfar:

1 - o SQL está errado SET `Campo = Valor`, `Campo = Valor`...

2020-06-04 23:58 UTC, robsonoduarte commented on src/main/java/br/com/people/api/controller/PersonController.java
>          var person = dataBase.find(id);
Danilo no update vc precisa receber um Person como parametro e não o Id, mesma ideia do `post`

2020-06-04 23:58 UTC, robsonoduarte commented on src/main/java/br/com/people/api/controller/PersonController.java
> +    @PatchMapping(value = "/{id}")
@Danilosimoes para realizar update utilizamos o verbo PUT do HTTP

2020-06-04 23:58 UTC, robsonoduarte commented on src/main/java/br/com/people/api/controller/PersonController.java
> +        var person = dataBase.find(id);
@Danilosimoes retirar essa linha já que ela e para fazer o select

2020-06-05 00:00 UTC, robsonoduarte commented
@Danilosimoes use o crtl + alt + L do Intellij para formatar o código

2020-06-05 00:04 UTC, robsonoduarte commented
@Danilosimoes percebe que tu criou os metodos na classe DB mais não usou no Controller

2020-06-05 00:10 UTC, merged

2020-06-05 00:11 UTC, Danilosimoes commented
Ahh bleza, eu entendi, valeu, vou fazer essas alterações citadas